### PR TITLE
DNM - Debug openssl3 migration issues on Windows 

### PR DESCRIPTION
**Pull request by jaimergp**
Comes from https://github.com/conda-forge/cryptography-feedstock/pull/98#issuecomment-1203923215

### CODE REVIEW

**Comment by h-vetinari** [comment]
Did you do this manually? I just did it as well via conda_build_config.yaml, but the rerender is taking a while.

**Comment by h-vetinari** [comment]
Do you mind if push into this PR?

**Comment by jaimergp** [comment]
Yep, I figured the rerender would take ages so just went ahead and did it manually with some Bash and multi-cursor magic. However it doesn't seem to work 🤣

**Comment by jaimergp** [comment]
> Do you mind if push into this PR?

Please go ahead!

**Comment by h-vetinari** [comment]
Ah, next problem. We only have a few CPython builds against OpenSSL 3 - certainly none of the old ones...

**Comment by jaimergp** [comment]
That's a big bummer :(

**Comment by jaimergp** [comment]
Summary:

(🚫 didn't solve, ❌ tests failed, ✅ passed)

🚫: Python 3.7.0 (Failing after 5m)
🚫: Python 3.7.6 (Failing after 5m)
❌: Python 3.7.12 (Failing after 25m)

🚫: Python 3.8.0 (Failing after 5m)
🚫: Python 3.8.3 (Failing after 5m)
🚫: Python 3.8.5 (Failing after 4m)
🚫: Python 3.8.10 (Failing after 5m)
✅: Python 3.8.13 (Successful in 18m)

🚫: Python 3.9.0 (Failing after 4m)
❌: Python 3.9.10 (Failing after 25m)
❌: Python 3.9.13 (Failing after 31m)
🚫: Python 3.9.4 (Failing after 4m)
🚫: Python 3.9.6 (Failing after 5m)

❌: Python 3.10.0 (Failing after 25m)
❌: Python 3.10.2 (Failing after 26m)
❌: Python 3.10.5 (Failing after 26m)

**Pull request closed without merging**
