### PR TITLE
Build against openssl 3.1

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- https://github.com/conda-forge/postgresql-feedstock/issues/178

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/cryptography i guess i don't understand how to do what i'm trying to do here... any thoughts on getting a `cryptography` built against `openssl 3.1.x` while the postgres compatibility stuff gets squared away?

**Comment by bollwyvl** [comment]
@conda-forge/cryptography guess this ready for review... `vectors` pulls in `3.2.0` on the `3.1.x` builds, but maybe that's not a huge deal?

**Comment by h-vetinari** [comment]
> any thoughts on getting a `cryptography` built against `openssl 3.1.x` while the postgres compatibility stuff gets squared away?

What part of postgres is still broken? There are _lots_ of cryptography builds against openssl 3.1, just not the very latest. Certainly enough to resolve an environment, especially because cryptography doesn't have a run-export that forces use of the newest version everywhere.

I'd rather fix things correctly regarding postgres than build twice here.

**Comment by bollwyvl** [comment]
The very latest cryptography ships some fixes for a found-this-week CVE.
Currently can't install any version of libpq against this version.

**Comment by h-vetinari** [comment]
Seems we have a test failure on linux now...

```
=================================== FAILURES ===================================
________________ TestRSADecryption.test_decrypt_invalid_decrypt ________________

self = <tests.hazmat.primitives.test_rsa.TestRSADecryption object at 0x7f7935f61390>
rsa_key_2048 = <cryptography.hazmat.backends.openssl.rsa._RSAPrivateKey object at 0x7f7935507c90>
backend = <OpenSSLBackend(version: OpenSSL 3.2.0 23 Nov 2023, FIPS: False, Legacy: True)>

    @pytest.mark.supported(
        only_if=lambda backend: (
            backend.rsa_encryption_supported(padding.PKCS1v15())
            and not backend._lib.Cryptography_HAS_IMPLICIT_RSA_REJECTION
        ),
        skip_message="Does not support PKCS1v1.5.",
    )
    def test_decrypt_invalid_decrypt(
        self, rsa_key_2048: rsa.RSAPrivateKey, backend
    ):
        private_key = rsa_key_2048
>       with pytest.raises(ValueError):
E       Failed: DID NOT RAISE <class 'ValueError'>

tests/hazmat/primitives/test_rsa.py:1793: Failed
```

**Comment by bollwyvl** [comment]
No worries at all, thanks for taking the time to make it happen.

**Comment by bollwyvl** [comment]
just confirmed this makes it possible to _solve_... will be tomorrow before i can actually test whether they all _work_ together. thanks again!

**Pull request merged**
